### ISSUE TITLE
Mentee: Eric Miller

### ISSUE THREAD

**Issue by eric-miller** [cjkoepke/code-mentors#1]
Hi Calvin,
I like what you've started here. I would love to get involved. I know all to well that many people are living in rural areas, leaving them with very little for support.

**Comment by cjkoepke** [comment]
Hey @eric-miller, thanks for getting involved! If you would like to be mentored, could you add a bit more detail about what language or system you wish to grow in, and where you are at experience-wise with it? This will help a mentor determine more easily if you would be a good fit.

Also, if you are even somewhat experienced in a given language, definitely fork the repo and [become a mentor](http://github.com/cjkoepke/code-mentors#become-a-mentor)!

**Comment by eric-miller** [comment]
My apologies, I don't think I would do any mentor, or mentee, justice with my limited time in the next couple months. As much as I hate to say it I have to put this on a back burner. 

I think the idea is great. I hope to see it become a community of networking and relationship building, not just a stackoverflow.

I would love to come back around to this in the fall when things slow down some.

**Comment by cjkoepke** [comment]
@eric-miller Please do!
