### ISSUE TITLE
Mentee: Timothy Jensen

### ISSUE THREAD

**Issue by timothyjensen** [cjkoepke/code-mentors#4]
Hey Calvin, this is a great idea.  I have been steadily improving my PHP skills, but my JS skills are lagging behind.  I would love to get to the point where I am confident in building a plugin that has a moderate to heavy dose of jQuery or Javascript...more than just a couple dozen lines of code.

**Comment by cjkoepke** [comment]
@timothyjensen I've just sent you a private message on the Genesis Slack channel. Also, if you're interested, there are plenty of people who are looking for help in the PHP arena, and if you have experience I'm sure you'd be a great mentor as well. Just a thought. ;-)

If you're interested, check out [Becoming a Mentor](https://github.com/cjkoepke/code-mentors#become-a-mentor).
